USE fashion_chatbot;

CREATE TABLE IF NOT EXISTS store_faqs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    sample_question VARCHAR(255) NOT NULL UNIQUE,
    keywords VARCHAR(500) NOT NULL,
    answer TEXT NOT NULL,
    INDEX idx_store_faq_category (category)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO store_faqs(category, sample_question, keywords, answer) VALUES
('shipping', 'Shop có giao hàng không?', 'shop co giao hang khong|giao hang|co ship khong|shop co ship|ship', 'Shop có hỗ trợ giao hàng. Bạn cho mình biết sản phẩm cần mua để được tư vấn tiếp nhé.'),
('shipping', 'Shop có ship không?', 'shop co ship khong|ship khong|van chuyen khong|ship', 'Shop có hỗ trợ giao hàng. Bạn cho mình biết sản phẩm cần mua để được tư vấn tiếp nhé.'),
('shipping_fee', 'Phí giao hàng là bao nhiêu?', 'phi giao hang la bao nhieu|phi giao hang|phi ship|cuoc van chuyen|tien ship|phi', 'Thông tin mẫu của đồ án: phí giao hàng là 25.000đ nội thành, 35.000đ ngoại tỉnh, miễn phí đơn từ 500.000đ. Hãy thay mức phí này bằng chính sách thật của shop trước khi sử dụng.'),
('shipping_fee', 'Phí ship bao nhiêu?', 'phi ship bao nhieu|phi ship|tien ship|cuoc ship|phi', 'Thông tin mẫu của đồ án: phí giao hàng là 25.000đ nội thành, 35.000đ ngoại tỉnh, miễn phí đơn từ 500.000đ. Hãy thay mức phí này bằng chính sách thật của shop trước khi sử dụng.'),
('shipping_time', 'Thời gian giao hàng bao lâu?', 'thoi gian giao hang bao lau|giao hang mat bao lau|giao hang bao lau|bao lau nhan hang', 'Thông tin mẫu của đồ án: đơn nội thành giao khoảng 1–2 ngày làm việc, đơn tỉnh khoảng 3–5 ngày làm việc. Thời gian có thể thay đổi theo khu vực.'),
('shipping_time', 'Đơn hàng khi nào tới?', 'don hang khi nao toi|khi nao nhan duoc hang|bao gio nhan hang|thoi gian nhan hang', 'Thông tin mẫu của đồ án: đơn nội thành giao khoảng 1–2 ngày làm việc, đơn tỉnh khoảng 3–5 ngày làm việc. Thời gian có thể thay đổi theo khu vực.'),
('shipping_area', 'Shop có giao hàng toàn quốc không?', 'giao hang toan quoc|ship toan quoc|giao toan quoc|pham vi giao hang', 'Thông tin mẫu của đồ án: shop nhận giao hàng trên toàn quốc. Hãy xác nhận lại phạm vi giao hàng thật của shop.'),
('shipping_area', 'Shop có giao hàng hỏa tốc không?', 'giao hang hoa toc|ship hoa toc|giao nhanh|hoa toc', 'Thông tin giao hàng hỏa tốc chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận dịch vụ hiện có.'),
('order_tracking', 'Tôi kiểm tra đơn hàng ở đâu?', 'kiem tra don hang|tra cuu don hang|theo doi don hang|trang thai don hang', 'Chatbot hiện chưa kết nối chức năng tra cứu đơn hàng. Bạn vui lòng liên hệ shop và cung cấp mã đơn để được hỗ trợ.'),
('shipping_address', 'Tôi muốn đổi địa chỉ giao hàng', 'doi dia chi giao hang|sua dia chi nhan hang|thay doi dia chi giao hang', 'Chatbot chưa hỗ trợ tự sửa địa chỉ đơn hàng. Bạn vui lòng liên hệ shop sớm và cung cấp mã đơn.'),
('payment', 'Shop hỗ trợ thanh toán bằng cách nào?', 'shop ho tro thanh toan bang cach nao|phuong thuc thanh toan|thanh toan nhu the nao', 'Shop hiện hỗ trợ thanh toán khi nhận hàng và chuyển khoản ngân hàng.'),
('payment', 'Có được thanh toán khi nhận hàng không?', 'thanh toan khi nhan hang|cod|tra tien khi nhan hang|nhan hang moi tra tien', 'Có. Shop hỗ trợ thanh toán khi nhận hàng.'),
('payment', 'Shop có nhận chuyển khoản không?', 'chuyen khoan|thanh toan qua ngan hang|so tai khoan', 'Có. Shop hỗ trợ chuyển khoản ngân hàng. Vui lòng liên hệ shop để nhận thông tin chuyển khoản chính xác.'),
('payment', 'Shop có thanh toán bằng thẻ không?', 'thanh toan bang the|the tin dung|the ngan hang|visa|mastercard', 'Thông tin thanh toán bằng thẻ chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận.'),
('payment', 'Shop có hỗ trợ trả góp không?', 'tra gop|mua tra gop|thanh toan tra gop', 'Thông tin trả góp chưa được cập nhật trong hệ thống. Bạn vui lòng liên hệ shop để xác nhận.'),
('payment', 'Tôi có thể trả tiền sau khi nhận hàng không?', 'tra tien sau khi nhan hang|nhan hang roi thanh toan|thanh toan sau', 'Có. Shop hiện có hình thức thanh toán khi nhận hàng.'),
('payment', 'Shop có xuất hóa đơn không?', 'xuat hoa don|hoa don mua hang|hoa don VAT|hoa don gia tri gia tang', 'Thông tin xuất hóa đơn chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận trước khi đặt hàng.'),
('store_address', 'Cửa hàng ở đâu?', 'cua hang o dau|dia chi cua hang|dia chi shop|shop o dau|chi nhanh o dau', 'Thông tin mẫu của đồ án: cửa hàng tại 123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh. Đây là địa chỉ minh họa, hãy thay bằng địa chỉ thật của shop.'),
('store_address', 'Địa chỉ shop là gì?', 'dia chi shop la gi|shop nam o dau|cua hang nam o dau|dia diem cua hang', 'Thông tin mẫu của đồ án: cửa hàng tại 123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh. Đây là địa chỉ minh họa, hãy thay bằng địa chỉ thật của shop.'),
('store_hours', 'Mở cửa lúc mấy giờ?', 'mo cua luc may gio|gio mo cua|gio lam viec|thoi gian mo cua', 'Thông tin mẫu của đồ án: shop mở cửa hằng ngày từ 09:00 đến 21:00. Hãy thay bằng giờ hoạt động thật của shop.'),
('store_hours', 'Shop mở cửa ngày chủ nhật không?', 'shop mo cua chu nhat|cua hang mo cua chu nhat|chu nhat co lam viec khong', 'Theo lịch mẫu của đồ án, shop mở cửa Chủ nhật từ 09:00 đến 21:00. Hãy thay bằng lịch thật của shop.'),
('store_hours', 'Ngày lễ shop có mở cửa không?', 'ngay le shop co mo cua|lich nghi le|shop nghi ngay nao', 'Lịch ngày lễ cần được shop xác nhận, giờ hoạt động thông thường theo dữ liệu mẫu là 09:00–21:00.'),
('store_contact', 'Số điện thoại của shop là gì?', 'so dien thoai shop|hotline cua hang|goi shop so nao|so lien he', 'Số điện thoại liên hệ chưa được cập nhật trong hệ thống. Bạn vui lòng xem thông tin liên hệ chính thức của shop.'),
('store_contact', 'Shop có email không?', 'email cua shop|dia chi email|gui email cho shop', 'Email liên hệ chưa được cập nhật trong hệ thống. Bạn vui lòng xem thông tin liên hệ chính thức của shop.'),
('store_contact', 'Làm sao để liên hệ với shop?', 'lien he voi shop|cach lien lac cua hang|nhan vien tu van|ket noi voi shop', 'Kênh liên hệ của shop chưa được cập nhật trong chatbot. Bạn vui lòng xem trang thông tin chính thức của cửa hàng.'),
('store_contact', 'Shop có cửa hàng trực tiếp không?', 'shop co cua hang truc tiep|co the den thu do|mua truc tiep|den cua hang', 'Thông tin cửa hàng trực tiếp chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận.'),
('return_policy', 'Chính sách đổi trả của shop thế nào?', 'chinh sach doi tra|quy dinh doi tra|doi tra nhu the nao|doi hang tra hang', 'Thông tin mẫu của đồ án: hỗ trợ đổi size/đổi mẫu trong 7 ngày từ khi nhận hàng nếu sản phẩm chưa qua sử dụng, còn tem nhãn và hóa đơn. Hãy thay bằng chính sách thật của shop.'),
('return_policy', 'Tôi đổi sang size khác được không?', 'doi sang size khac|doi size|doi kich co|doi size ao', 'Theo chính sách mẫu của đồ án, bạn có thể yêu cầu đổi size trong 7 ngày nếu sản phẩm chưa qua sử dụng, còn tem nhãn và hóa đơn, vui lòng liên hệ shop để kiểm tra tồn kho.'),
('return_policy', 'Thời hạn đổi trả là bao lâu?', 'thoi han doi tra|doi tra trong bao lau|bao nhieu ngay duoc doi|han doi hang', 'Thời hạn đổi trả mẫu là 7 ngày từ khi nhận hàng. Đây là dữ liệu minh họa, cần thay theo chính sách thật của shop.'),
('return_policy', 'Sản phẩm lỗi thì xử lý thế nào?', 'san pham bi loi|hang bi loi|loi san pham|nhan hang bi hong', 'Theo chính sách mẫu, hãy chụp ảnh sản phẩm và liên hệ shop trong vòng 7 ngày từ khi nhận hàng để được kiểm tra và hỗ trợ.'),
('return_policy', 'Bao lâu tôi được hoàn tiền?', 'bao lau duoc hoan tien|thoi gian hoan tien|khi nao nhan lai tien', 'Thời gian hoàn tiền tùy phương thức thanh toán, shop cần xác nhận thời hạn cụ thể. Chính sách mẫu yêu cầu liên hệ shop sau khi yêu cầu đổi trả được duyệt.'),
('return_policy', 'Tôi muốn hủy đơn hàng', 'huy don hang|muon huy don|cancel don hang', 'Chatbot chưa hỗ trợ hủy đơn tự động. Bạn vui lòng liên hệ shop sớm và cung cấp mã đơn.'),
('return_policy', 'Phí đổi trả do ai chịu?', 'phi doi tra|ai chiu phi ship doi hang|phi van chuyen doi tra', 'Theo chính sách mẫu của đồ án, shop chịu phí nếu sản phẩm lỗi, khách chịu phí nếu đổi do nhu cầu cá nhân. Hãy thay theo chính sách thật của shop.'),
('promotion', 'Shop đang có khuyến mãi gì?', 'shop dang co khuyen mai gi|chuong trinh khuyen mai|uu dai hien tai|giam gia hom nay', 'Thông tin khuyến mãi hiện chưa được cập nhật trong chatbot. Bạn vui lòng xem thông báo mới nhất từ shop.'),
('promotion', 'Shop có mã giảm giá không?', 'ma giam gia|voucher cua shop|ma voucher|nhap ma giam gia|voucher', 'Mã giảm giá chưa được cập nhật trong hệ thống. Bạn vui lòng xem chương trình ưu đãi hiện hành của shop.'),
('promotion', 'Có được miễn phí giao hàng không?', 'mien phi giao hang|free ship|khong mat phi ship|uu dai van chuyen', 'Chương trình miễn phí giao hàng chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận điều kiện áp dụng.'),
('promotion', 'Shop có tích điểm thành viên không?', 'tich diem thanh vien|the thanh vien|diem thuong|uu dai thanh vien', 'Thông tin chương trình thành viên chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận.'),
('promotion', 'Mua nhiều có được giảm giá không?', 'mua nhieu giam gia|giam gia don hang lon|uu dai mua so luong|chiet khau', 'Ưu đãi theo số lượng chưa được cập nhật. Bạn vui lòng liên hệ shop để được báo giá chính xác.'),
('product_support', 'Shop có ảnh sản phẩm không?', 'anh san pham|hinh anh san pham|xem hinh mau|cho xem anh|anh', 'Cơ sở dữ liệu hiện chưa lưu ảnh sản phẩm. Bạn có thể hỏi tên, màu, size hoặc mô tả của sản phẩm để chatbot tra cứu thông tin đang có.'),
('product_support', 'Tư vấn size giúp tôi', 'tu van size|chon size nao|size nao phu hop|tu van kich co|size', 'Mình có thể hỗ trợ chọn size. Bạn cho biết sản phẩm muốn mặc, giới tính, chiều cao và cân nặng nhé.'),
('product_support', 'Làm sao biết sản phẩm còn hàng?', 'kiem tra con hang|san pham con hang khong|ton kho san pham|con mau va size khong', 'Chatbot có thể kiểm tra tồn kho từ dữ liệu sản phẩm. Bạn gửi tên sản phẩm cùng màu hoặc size muốn tìm nhé.'),
('product_support', 'Làm sao đặt mua sản phẩm?', 'cach dat mua san pham|dat hang nhu the nao|mua hang nhu the nao|tao don hang', 'Chatbot hiện hỗ trợ tư vấn và tra cứu sản phẩm, chưa tạo đơn hàng tự động. Bạn vui lòng liên hệ shop để đặt mua.'),
('product_support', 'Shop có gói quà không?', 'goi qua|goi lam qua tang|dong goi qua tang|hop qua', 'Thông tin gói quà chưa được cập nhật. Bạn vui lòng liên hệ shop để xác nhận dịch vụ hiện có.')
ON DUPLICATE KEY UPDATE
    category = VALUES(category),
    keywords = VALUES(keywords),
    answer = VALUES(answer);
